modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/RandomEconomy/issues"
license = "All Right Reserved"

[[mods]]
modId = "random_economy"
version = "${version}"
displayName = "Random Economy"
authors = "IAFEnvoy, HF_ColdWind"
description = '''
An item based economy system.
'''
logoFile = "logo.jpg"

[[dependencies.random_economy]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_economy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_economy]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
